- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove existing folder
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Create folder
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Download Frontend app code and unzip it
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy the Roboshop configuration file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Copy the nginx configuration file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Run tasks from elk role
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: Start and Run nginx
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true