#echo -e "************\e[36m Enable & Start NGINX ************\e[0m"
#systemctl enable nginx
#systemctl start nginx
#
#echo -e "************\e[36m Copy Roboshop Config file ************\e[0m"
#cp /home/centos/roboshop-shell/roboshop.conf /etc/nginx/default.d/roboshop.conf
#
#echo -e "************\e[36m ReStart NGINX ************\e[0m"
#systemctl restart nginx

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove existing folder
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Create folder
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Download Frontend app code and unzip it
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy the Roboshop configuration file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start and Run nginx
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true