- name: Create roboshop functional user
  ansible.builtin.user:
    name: "{{ app_user }}"

- name: Remove existing folder
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create folder
  ansible.builtin.file:
    path: /app
    state: directory

#- name: Download Catalogue app code and unzip it
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
#    dest: /app
#    remote_src: yes

- name: Download app code from Nexus and Unzip
  ansible.builtin.unarchive:
    src: http://172.31.34.184:8081/repository/{{ component }}/{{ component }}-{{app_version}}.zip
    dest: /app
    remote_src: yes