- name: print component value
  ansible.builtin.debug:
    msg : Component - {{ component }}

- name: Create roboshop functional user
  ansible.builtin.user:
    name: "{{ app_user }}"

- name: Remove existing folder
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create folder
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download Catalogue app code and unzip it
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: yes
