- name: Install NodeJs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Import app_setup tasks into this play
  ansible.builtin.import_tasks:
    file: app_setup.yml

# Dependencies are installed through build pipeline
#- name: Install nodeJs dependencies
#  ansible.builtin.shell: npm install
#  args:
#    chdir: /app

- name: Load mongodb schema - Import tasks into this play
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: Systemd Enable & Restart Service
  ansible.builtin.import_tasks:
    file: systemd_setup.yml

- name: Run tasks from prometheus role
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter