- name: Schema Setup for mongodb
  block:
    - name: Copy the mongodb repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install mongodb
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: Download DocumentDb PEM file
      ansible.builtin.get_url:
        url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
        dest: /app/rds-combined-ca-bundle.pem

    - name: Load Mongo schema
      ansible.builtin.shell: mongo --ssl --host {{ lookup('aws_ssm', 'dev.catalogue.mongo_endpoint', region='us-east-1' ) }}:27017 --sslCAFile /app/rds-combined-ca-bundle.pem --username {{ lookup('aws_ssm', 'dev.docdb.db_user', region='us-east-1' ) }} --password {{ lookup('aws_ssm', 'dev.docdb.db_pwd', region='us-east-1' ) }}</app/schema/{{ component }}.js
  when: schema_setup == "mongodb"

- name: Schema Setup for MySQL
  block:
    - name: Install MySQL
      ansible.builtin.yum:
        name: mysql
        state: installed
    - name: Load MySQL schema
      ansible.builtin.shell: mysql -h {{ lookup('aws_ssm', 'dev.shipping.rds.nldevopsb01_endpoint', region='us-east-1' ) }} -u{{ lookup('aws_ssm', 'dev.rds.db_userr', region='us-east-1' ) }} -p{{ lookup('aws_ssm', 'dev.rds.db_pwd', region='us-east-1' ) }} < /app/schema/{{component}}.sql
  when: schema_setup == "mysql"

