- name: Copy the logstash configuration file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart prometheus Service
  ansible.builtin.systemd_service:
    name: prometheus
    enabled: true
    state: restarted

- name: Prometheus service running check
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 15