- name: Copy the Prometheus/alerts configuration file
  ansible.builtin.template:
    src: "{{item}}".yml
    dest: /opt/prometheus/{{item}}.yml
  loop:
    - prometheus
    - alert

- name: Restart prometheus Service
  ansible.builtin.systemd_service:
    name: prometheus
    enabled: true
    state: restarted

- name: Prometheus service running check
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 15